name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift_version: ["5.0", "5.1"]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run swift ${{ matrix.swift_version }} test
      run: docker run -v ${{ github.workspace }}:/mnt -w /mnt swift:${{ matrix.swift_version }} swift test
